### ISSUE TITLE
Possible typo when copying from mhsave manager ItemServices file

### ISSUE THREAD

**Issue by EclipseKnight** [HadziqM/Rain-rust-bot#1]
I noticed on [this line](https://github.com/HadziqM/Rain-rust-bot/blob/2bfb9e67c73799ad89aae3396c543055d409f38d/src/material/melee.rs#L9329l) you seem to have the '7019 =>' which seems to be based on the EquipService php formatting from mhsavemanager where this list was likely pulled and edited from to an extent. Thought I'd let you know just in case this ever appears as an issue.

**Comment by HadziqM** [comment]
thx for reminding, i literally never touch this for some time
